### ISSUE TITLE
Example video of results

### ISSUE THREAD

**Issue by ck37** [z-x-yang/AOT#12]
Hello,

Is it possible to provide an example video or two which demonstrate the results of the method?

Thanks,
Chris

**Comment by z-x-yang** [comment]
Hi Chris,

[Here](https://drive.google.com/file/d/1XNU0IXVYGtJHAYsT_u0gFEQF2KWzq-yw/view?usp=sharing) is the latest results (YouTube-VOS 2018 and DAVIS 2017) of AOT-L. Most of the results are slightly higher than the reported ones in our paper. All the results were predicted by an identical AOT-L model, which was trained yesterday. 

I'm currently working on adjusting the training hyper-parameters since I found the reported results were not perfect because of overfitting. I believe this will be done in a few days.

Best,
Zongxin

**Comment by z-x-yang** [comment]
Hi Chris,

An implementation of AOT is available [here](https://github.com/yoxu515/aot-benchmark).

Best,

Zongxin
